### ISSUE TITLE
Add to test suit: check that alla UUid:s are unique

### ISSUE THREAD

**Issue by magan6** [welfare-state-analytics/blm-corpus#21]

**Comment by MansMeg** [comment]
You dont need to check this. It is veeery unlikely they will not be unique.

**Comment by magan6** [comment]
I can agree with that, although as we have many nested loops, and when importing the uuid function from an utils.py file, there can be difficulties with setting the seed at the right location. As Liam noticed today. Therefore it can be useful to have such a test.

**Comment by MansMeg** [comment]
Ok. You should not set the seed for the uuid function. Instead use the current second as the seed in the very beginning of the script.

**Comment by magan6** [comment]
Ah, will look that up. Found something regarding "timestamp-first UUIDs" (https://www.uuidtools.com/uuid-versions-explained). Is that what you refer to?

**Comment by liamtabib** [comment]
We can use the current time as the seed, which would give us new uuids every time we release a new version by running the script. Could this be problematic since we will have to run the metadata script in conjunction with every new release, as the metadata points to the blm corpus uuid in the previous version? If we have a fixed seed we can avoid this issue?
What is your opinion Måns ?

**Comment by liamtabib** [comment]
This problem will persist even if we use a fixed seed, as the order of the uuids will change since our segmentation into elements changes with every release (more headers correctly identified, review etc). 
Therefore maybe we should think about whether to include the uuid in the metadata/goldstandard csv at all, or how to avoid this potential issue.

**Comment by MansMeg** [comment]
So the uuid should only be created once when the data is created and stored with the data. So you should not need to recreate the uuids.
